services:
  - type: web
    name: trustbite-app
    env: node
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: cd backend/src && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20
